const fs = require('fs');
const d = require('docx');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun,
        Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType, PageBreak } = d;

// ---------- helpers ----------
const FONT = "Calibri";
function P(text, opts={}) {
  const runs = Array.isArray(text) ? text : [new TextRun({ text, ...opts.run })];
  return new Paragraph({ children: runs, spacing:{after:120, line:276}, ...opts.par });
}
function H1(t){ return new Paragraph({ heading:HeadingLevel.HEADING_1, spacing:{before:240,after:120},
  children:[new TextRun({text:t, bold:true, size:28, font:FONT})]}); }
function H2(t){ return new Paragraph({ heading:HeadingLevel.HEADING_2, spacing:{before:180,after:100},
  children:[new TextRun({text:t, bold:true, size:24, font:FONT})]}); }
function H3(t){ return new Paragraph({ heading:HeadingLevel.HEADING_3, spacing:{before:140,after:80},
  children:[new TextRun({text:t, bold:true, italics:true, size:22, font:FONT})]}); }
function T(text, o={}){ return new TextRun({ text, font:FONT, size:22, ...o }); }
function para(children, o={}){ return new Paragraph({ children, spacing:{after:120, line:276}, ...o }); }
function body(text){ return new Paragraph({ children:[T(text)], spacing:{after:120, line:276}, alignment:AlignmentType.JUSTIFIED }); }
function authorNote(text){ return new Paragraph({ spacing:{after:120,line:276},
  shading:{type:ShadingType.CLEAR, fill:"FFF2CC"},
  children:[new TextRun({text:"[AUTHORS → "+text+"]", italics:true, color:"9C6500", size:20, font:FONT})]}); }
function img(path, w, h, type){ return new Paragraph({ alignment:AlignmentType.CENTER, spacing:{before:120,after:60},
  children:[new ImageRun({ type, data:fs.readFileSync(path), transformation:{width:w, height:h} })]}); }
function legend(num, rest){ return new Paragraph({ spacing:{after:160,line:276}, children:[
  new TextRun({text:"Fig. "+num+" ", bold:true, font:FONT, size:20}),
  new TextRun({text:rest, font:FONT, size:20})]}); }

// table builder: rows = array of arrays; first row header
function makeTable(rows, widths){
  const total = widths.reduce((a,b)=>a+b,0);
  const trs = rows.map((r,ri)=> new TableRow({ tableHeader: ri===0, children: r.map((c,ci)=>
    new TableCell({ width:{size:widths[ci], type:WidthType.DXA},
      shading: ri===0 ? {type:ShadingType.CLEAR, fill:"D9E2F3"} : undefined,
      children:[ new Paragraph({ spacing:{after:20,line:240}, children:[ new TextRun({ text:String(c),
        bold: ri===0, font:FONT, size:18 }) ] }) ] }))}));
  return new Table({ columnWidths:widths, width:{size:total,type:WidthType.DXA}, rows:trs });
}
function tblCap(text){ return new Paragraph({ spacing:{before:60,after:180,line:252}, children:[
  new TextRun({text:text.split("|")[0], bold:true, font:FONT, size:18}),
  new TextRun({text:text.split("|").slice(1).join("|"), font:FONT, size:18})]}); }

const children = [];
const push = (...x)=>x.forEach(e=>children.push(e));

// ================= TITLE =================
push(new Paragraph({ alignment:AlignmentType.CENTER, spacing:{after:120},
  children:[new TextRun({text:"Descriptor Selection for Small-Sample QSAR: Selection Bias, Nested Validation and the n:p Ratio Problem", bold:true, size:30, font:FONT})]}));
push(new Paragraph({ alignment:AlignmentType.CENTER, spacing:{after:60},
  children:[new TextRun({text:"Julia Werle", size:22, font:FONT}), new TextRun({text:"1,2", size:14, superScript:true, font:FONT}),
            new TextRun({text:", Johana Rondevaldova", size:22, font:FONT}), new TextRun({text:"1", size:14, superScript:true, font:FONT}),
            new TextRun({text:", Egon Werle", size:22, font:FONT}), new TextRun({text:"3", size:14, superScript:true, font:FONT})]}));
push(new Paragraph({ spacing:{before:80,after:20}, children:[
  new TextRun({text:"1 ",superScript:true,size:16,font:FONT}),
  new TextRun({text:"Department of Crop Sciences and Agroforestry, Faculty of Tropical AgriSciences, Czech University of Life Sciences Prague, Kamycka 129, 165 00 Prague-Suchdol, Czech Republic.",size:18,font:FONT})]}));
push(new Paragraph({ spacing:{after:20}, children:[
  new TextRun({text:"2 ",superScript:true,size:16,font:FONT}),
  new TextRun({text:"Department of Medical Chemistry and Clinical Biochemistry, Second Faculty of Medicine, Charles University in Prague and Motol University Hospital, Prague, Czech Republic.",size:18,font:FONT})]}));
push(new Paragraph({ spacing:{after:20}, children:[
  new TextRun({text:"3 ",superScript:true,size:16,font:FONT}),
  new TextRun({text:"Department of Medicine I and Clinical Chemistry, Heidelberg University Hospital, Heidelberg, Germany.",size:18,font:FONT})]}));
push(new Paragraph({ spacing:{before:60,after:120}, children:[
  new TextRun({text:"Corresponding author: ",bold:true,size:20,font:FONT}),
  new TextRun({text:"Julia Werle (werle@ftz.czu.cz).",size:20,font:FONT})]}));
push(authorNote("Der frühere Titel „A Systematic Approach … Addressing the n:p Ratio Problem“ ist ebenfalls möglich – bitte final wählen."));

// ================= ABSTRACT =================
push(H1("Abstract"));
push(body("Quantitative structure–activity relationship (QSAR) modelling becomes unreliable when the number of molecular descriptors (p) approaches or exceeds the number of compounds (n) — the small-n, large-p problem that is characteristic of antimicrobial and natural-product datasets. Two descriptor-selection routes dominate the literature: computing very large descriptor pools and reducing them by correlation and univariate statistics, or pre-selecting a small set of chemically interpretable descriptors. Using 31 monoterpenoids tested against five pneumonia-associated bacterial strains, we show that the first route, when a supervised univariate filter (effect-size / Wilcoxon selection) is applied to the whole dataset before cross-validation, produces optimistically biased performance: the ordinary permutation test keeps the selected descriptors fixed and is therefore circular. Under fully nested validation — repeating descriptor selection inside every cross-validation fold and permuting the entire pipeline — the apparent predictive ability collapses (e.g. Haemophilus influenzae cross-validated Q² 0.43 → −0.14, not significant; Streptococcus pyogenes 0.52 → −0.11, not significant). Importantly, a weak but genuinely significant signal survived nesting for Staphylococcus aureus and Streptococcus pneumoniae (Q² 0.16 and 0.19; p = 0.013 and 0.010), so the procedure is not worthless — it can be meaningful for some endpoints provided it is honestly validated. The second route — 25 literature-derived, interpretable descriptors reduced only by unsupervised correlation grouping (which uses no activity labels and is therefore leakage-free) — recovered an honestly significant, moderate signal for H. influenzae, S. aureus and S. pneumoniae (Q² 0.29–0.39, p ≤ 0.003) even with a single latent variable. A two-stage variable-importance (VIP) selection, in which high-VIP descriptors from a first model are re-used in a second, reproduces the same optimistic bias unless the VIP step is itself nested. We conclude with practical guidance for descriptor selection under an unfavourable n:p ratio."));
push(new Paragraph({ spacing:{after:60}, children:[new TextRun({text:"Scientific contribution", bold:true, font:FONT, size:22})]}));
push(body("We show, on a real small-sample antimicrobial dataset, that the apparent success of supervised descriptor-selection filters in small-n QSAR is largely an artefact of selection bias, and that only fully nested validation with whole-pipeline permutation gives an honest performance estimate. We further demonstrate that an unsupervised, correlation-only reduction of a small, theory-driven descriptor set is leakage-free and recovers a genuine signal where the data-driven route fails, and we provide a decision framework for choosing and validating descriptors when p ≈ or > n."));
push(new Paragraph({ spacing:{after:120}, children:[
  new TextRun({text:"Keywords: ", bold:true, font:FONT, size:22}),
  new TextRun({text:"molecular descriptors; QSAR; feature selection; small sample size; n:p ratio; nested cross-validation; selection bias; permutation testing; PLS-DA; monoterpenoids", font:FONT, size:22})]}));

// ================= INTRODUCTION =================
push(H1("Introduction"));
push(body("Quantitative structure–activity relationship (QSAR) modelling predicts biological activity from molecular structure and is an established tool in early drug discovery and natural-product research [refs]. Its central premise is that activity is encoded in quantifiable molecular features whose relationship to a measured endpoint can be captured by a statistical model. In practice, why some closely related compounds are active while others are not can rarely be explained by a handful of classical physicochemical parameters; capturing the relevant structural and electronic information usually requires large, computationally generated descriptor sets. This is the origin of the statistical difficulty addressed here."));
push(body("Modern platforms generate thousands of descriptors from structure alone, whereas activity-driven studies — natural-product discovery and early medicinal chemistry in particular — are limited to tens of compounds by synthesis, isolation and assay costs [refs]. The number of descriptors (p) then greatly exceeds the number of samples (n): the small-n, large-p problem, or curse of dimensionality. In this regime the multivariate methods most used in QSAR can produce apparent separation of random data; Ruiz-Pérez and colleagues showed with synthetic data that partial least squares discriminant analysis (PLS-DA) is reliable only around a sample-to-feature ratio of roughly 2:1 [Ruiz-Pérez et al.]. Controlling the n:p ratio is therefore a prerequisite for any trustworthy small-sample model, not a cosmetic refinement."));
push(body("Two descriptor-selection strategies recur in the literature. The first computes a very large descriptor pool from one or more libraries and reduces it — typically by correlation filtering followed by a univariate statistical criterion (for example a rank-sum test with an effect-size threshold), sometimes followed by re-selection of high variable-importance-in-projection (VIP) descriptors. The second pre-selects a small number of chemically interpretable descriptors on mechanistic grounds and reduces residual redundancy by correlation only. Both are widely used, but their statistical validity in the small-n regime is rarely examined critically."));
push(body("A crucial and under-appreciated distinction separates the two. Correlation filtering between descriptors is unsupervised — it never uses the activity labels — and is therefore leakage-free. A univariate effect-size filter, or a VIP-based re-selection, is supervised: it uses the labels. When such a supervised selection is performed on the whole dataset before cross-validation, the left-out samples have already influenced which descriptors are retained, so the cross-validated error and any permutation test that keeps the selection fixed are optimistically biased [Ambroise & McLachlan; Varma & Simon; Krstajić et al.]. With p ≫ n this bias is severe, because some descriptors always separate a given small dataset by chance [Golbraikh & Tropsha; Rücker et al.]. An honest estimate requires that the entire supervised selection be repeated inside every cross-validation fold (nested validation) and that permutation tests randomise the labels through the complete pipeline."));
push(body("Here we examine both selection routes on a previously published dataset of 31 monoterpenoids tested against five pneumonia-associated bacterial strains [Werle et al. 2026] — a representative small-sample scenario. We first show that the large-pool route with a supervised effect-size filter yields high apparent performance that is largely removed by nested validation, but that a weak, genuinely significant signal nonetheless survives for two strains. We then show that the small, interpretable, unsupervised-reduced descriptor set is leakage-free and recovers a genuine moderate signal for three strains. Finally, we quantify the bias of the two-stage VIP procedure and give practical guidance for descriptor selection under an unfavourable n:p ratio."));
push(authorNote("Introduction: [ref]/[Name]-Platzhalter in nummerierte Referenzen umwandeln. Die method­ischen Kernreferenzen (Ambroise & McLachlan 2002; Varma & Simon 2006; Krstajić et al. 2014; Golbraikh & Tropsha 2002; Rücker et al. 2007) sind in der Referenzliste bereits verifiziert enthalten."));

// ================= MATERIALS AND METHODS =================
push(H1("Materials and methods"));
push(H2("Data set"));
push(body("The workflow was demonstrated on a previously published data set of 31 monoterpenoids tested against five pneumonia-associated bacterial strains (Haemophilus influenzae ATCC 49247, Pseudomonas aeruginosa ATCC 27853, Staphylococcus aureus ATCC 29213, Streptococcus pneumoniae ATCC 49619 and Streptococcus pyogenes ATCC 19615) [Werle et al. 2026]. Antibacterial activity in the liquid (broth) phase of the broth microdilution volatilization assay was the endpoint; for each strain compounds were assigned a binary class (active vs. non-active) from their mean minimum inhibitory concentration, giving five independent classification endpoints. The active/non-active split was 10/21 (H. influenzae), 3/28 (P. aeruginosa), 5/26 (S. aureus), 6/25 (S. pneumoniae) and 11/20 (S. pyogenes). P. aeruginosa, with only three actives, was treated as descriptive only and excluded from predictive claims."));
push(H2("The data set and its limitations"));
push(body("This data set was chosen deliberately for its imperfections, not despite them. With only 31 compounds it is small, and the active/inactive split is imbalanced and endpoint-specific — from a relatively balanced 10/21 and 11/20 (H. influenzae, S. pyogenes) to 5/26 and 6/25 (S. aureus, S. pneumoniae) and an extreme 3/28 for P. aeruginosa, which has too few actives for predictive modelling and is reported as descriptive only. The monoterpenoids form a narrow, structurally homogeneous chemical class, which supports mechanistic interpretation within the class but limits descriptor variance and external applicability. Activity was obtained by dichotomising minimum inhibitory concentrations from the standardised broth microdilution volatilisation assay against defined ATCC reference strains; the assay is reproducible, but dichotomisation discards information and makes the labels threshold-dependent, and borderline compounds can influence the small active class disproportionately. No external test set is available, so all estimates are internal. Against 2,208 cleaned descriptors, the initial sample-to-feature ratio of roughly 1:71 is far from the ~2:1 regarded as adequate for PLS-DA."));
push(body("These properties are exactly why the data set is instructive here. The aim of this study is to expose the problems and difficulties of descriptor selection followed by PLS-DA in the small-n, large-p regime; a small, imbalanced and chemically narrow set makes selection bias, overfitting and the instability of supervised selection visible in a way that a large, balanced, chemically diverse \u201cideal\u201d data set would not. A near-perfect data set would have produced cleaner models but would have been far less suited to the critical, methodological discussion that is the purpose of this work. Accordingly, all results are framed as associations within this data set rather than as validated predictors of new compounds."));

push(H2("Route A — large multi-library descriptor pool"));
push(H3("Stage 1 — Descriptor generation"));
push(body("Canonical SMILES from PubChem [Kim et al.] were used to compute descriptors on the ChemDes platform [Dong et al.] from five libraries — Chemopy (1,135 descriptors) [Cao et al.], PaDEL (1,975 descriptors) [Yap], RDKit (196 descriptors), BlueDesc (174 descriptors) and Pybel (27 descriptors) — giving 3,507 descriptors in total. Non-numerical, missing-value and autocorrelation descriptors were removed, together with exact duplicates and constant/near-zero-variance descriptors, reducing this initial pool of 3,507 to 2,208 numeric descriptors. No descriptor-class partitioning was applied and no OECD QSAR Toolbox descriptors were used."));
push(H3("Stage 2 — Correlation-based feature grouping (unsupervised)"));
push(body("Across the retained descriptors, Spearman (ρ) and Pearson (r) coefficients were computed and a descriptor pair treated as redundant when |ρ| > 0.7 or |r| > 0.7. Redundant descriptors were consolidated into feature groups by an iterative most-connected-first procedure adapted from Comesaña et al.; uncorrelated descriptors were retained individually. This step uses no activity labels and is therefore leakage-free."));
push(H3("Stage 3 — Supervised effect-size filtering"));
push(body("Each descriptor surviving Stage 2 was tested for its ability to discriminate active from non-active compounds with the Wilcoxon rank-sum test (Mann–Whitney U). The effect size was taken as the rank-biserial correlation (equivalently r = Z/√N) and interpreted by Cohen's guidelines; descriptors with p ≤ 0.05 and |r| > 0.3 were retained, and within each feature group the highest-effect-size descriptor was kept as representative. The p-values were not adjusted for multiple testing (no Benjamini–Hochberg or comparable correction); across the ~2,208 tests this inflates the false-positive rate, which is one reason the resulting selection must be validated by nesting rather than reported directly. This step is supervised."));
push(H3("Stage 4 — Final selection and n:p constraint"));
push(body("Representatives and singletons were pooled and, where a fixed model size was required, the highest-effect-size descriptors were retained to keep the sample-to-feature ratio near 2:1 (p ≤ n/2 ≈ 15 for n = 31) [Ruiz-Pérez et al.]."));

push(H2("Route B — small, literature-derived interpretable descriptors"));
push(body("Independently, 25 interpretable two-dimensional descriptors were selected a priori from the monoterpenoid structure–activity literature, spanning constitution (molecular weight, carbon and oxygen counts, heavy-atom and ring counts), saturation/shape (fraction of sp3 carbon, aliphatic/aromatic rings, C=C count, stereocentres, degree of unsaturation), functional groups (hydrogen-bond donors/acceptors and SMARTS indicators for aldehyde, ketone, carboxylic acid, phenol, ether, ester/lactone and aliphatic alcohol) and physicochemistry (Crippen logP and molar refractivity, Ertl TPSA, Labute ASA). All descriptors were computed with RDKit from neutral, canonical SMILES, without 3D optimisation or pH/protonation correction; rotatable bonds used the strict definition, aromaticity the RDKit default model, and stereocentres included unspecified centres. Exact definitions and SMARTS are given in the Additional file. Because this set is fixed a priori from external knowledge, it uses no activity information (leakage-free by construction). Residual redundancy was removed by the same unsupervised correlation grouping as in Stage 2 (|ρ| or |r| > 0.7), with rare binary indicators (fewer than four positive compounds) kept as singletons because their correlations are unstable at n = 31; this reduced the 25 descriptors to 13."));

push(H2("PLS-DA modelling and validation"));
push(body("Descriptor sets were modelled by PLS-DA with autoscaling and leave-one-out cross-validation (LOOCV). The number of latent variables was reported both at a parsimonious nLV = 1 and at the Q²-optimal value; nLV = 1 is the conservative, selection-independent estimate. Model quality was reported as the apparent explained variance (R²Y), the cross-validated Q² and the area under the ROC curve (AUC), with balanced accuracy, sensitivity, specificity and the Matthews correlation coefficient for classification. Statistical significance was assessed by a permutation test with 2,000 random relabelings, p = (1 + #{permuted ≥ observed}) / (1 + n)."));
push(body("The type of permutation test was matched to the selection step. For the supervised Route A, the effect-size filter and feature grouping were repeated inside every LOOCV fold on the training data only, and the 2,000 permutations randomised the labels through the complete pipeline (fully nested validation with whole-pipeline y-scrambling). For the unsupervised Route B, a simple permutation with the fixed descriptor set is already honest, because no supervised selection precedes the model; apparent and cross-validated performance therefore coincide. The two-stage VIP procedure was evaluated in a naive variant (VIP > 1 descriptors chosen on the whole dataset, then re-modelled) and a nested variant (VIP selection repeated inside each fold) to quantify its bias. Multiplicity across the five endpoints was addressed by a Bonferroni threshold (α = 0.01)."));
push(body("Concretely, each permutation randomised only the class-label vector; the descriptor matrix was left unchanged. For every permuted labelling the entire Route A pipeline was recomputed from scratch — the rank-biserial effect size and its p-value for all 2,208 descriptors, the p ≤ 0.05 and |r| > 0.3 filter, the correlation grouping, the top-k ranking and the PLS-DA fit — inside each leave-one-out fold on the training partition only. No effect size was reassigned between descriptors, and nothing selected on the real labels was carried over; because the descriptor ranks are label-independent they were pre-computed once, whereas the label-dependent effect size was re-evaluated in every permutation. This ensures that the advantage of choosing the best-separating descriptors from a large pool is itself contained in the null distribution — which an ordinary permutation that holds the selected descriptors fixed does not achieve."));
push(H2("Software"));
push(body("Route A descriptor calculation used the ChemDes platform (Chemopy, PaDEL, RDKit, BlueDesc and Pybel libraries); the correlation analysis and the illustrative PLS-DA score plot used MetaboAnalyst 5.0. Route B descriptors, the correlation-based reduction, all cross-validated and nested PLS-DA models, the permutation tests and VIP calculations were implemented in Python (RDKit 2026.03.3, scikit-learn, SciPy, pandas). All analysis scripts and data tables are provided as Additional files to ensure full reproducibility."));
push(H3("Use of large language models"));
push(body("A large language model (Claude Opus 4.8; Anthropic, PBC) was used, under the authors' direction and supervision, to assist with implementing the statistical-analysis code (in particular the nested cross-validation and whole-pipeline permutation procedures), generating figures, and drafting and editing the manuscript text. It was not used to generate or interpret the underlying biological activity data. All code, analyses, results and interpretations were reviewed and verified by the authors, who take full responsibility for the content. In accordance with COPE and Springer Nature policy, the model does not meet the criteria for authorship and is not listed as an author."));
push(authorNote("Software-Referenzen (ChemDes, PaDEL, Chemopy, RDKit, BlueDesc, Pybel, MetaboAnalyst, scikit-learn, SciPy) mit Version als nummerierte Zitate ergänzen. LLM-Offenlegung oben ist ein Vorschlag nach Springer-Nature/COPE-Vorgabe – bei Bedarf anpassen."));

// ================= CASE STUDY / RESULTS =================
push(H1("Case study: antimicrobial monoterpenoids"));
push(body("Both routes were applied to the 31-monoterpenoid data set. Route A started from 3,507 descriptors (five ChemDes libraries), reduced to 2,208 after cleaning — an initial ratio of about 1:71 for 31 compounds — which the selection stages reduced to strain-specific representative sets (31–53 descriptors; Table 1). Route B used the 25 pre-selected descriptors reduced to 13 by unsupervised correlation grouping. The framework is summarised in Fig. 1."));
push(img("/home/claude/ms_unpack/word/media/image1.jpg", 560, 249, "jpg"));
push(legend("1","Overview of the two descriptor-selection routes and the validation strategy. Route A (large multi-library pool → correlation grouping → supervised effect-size filter → n:p-constrained selection) is validated by fully nested cross-validation; Route B (small, literature-derived interpretable set → unsupervised correlation grouping) is leakage-free and validated by a simple permutation test."));
push(authorNote("Fig. 1 ist noch die ursprüngliche Vierstufen-Grafik. Für die überarbeitete Aussage bitte um die zweite (unsupervised) Route und den Nested-Validation-Schritt ergänzen, oder als Schema neu zeichnen."));

push(H2("Route A: apparent performance is removed by nested validation"));
push(body("With the supervised effect-size filter applied before cross-validation, Route A produced high apparent performance across strains (single-component models, apparent Q² up to ~0.5–0.9 and permutation p ≈ 0.0005). These values, however, are optimistically biased: the permutation test kept the label-selected descriptors fixed and therefore tested only the modelling step, not the selection. When the effect-size filter and feature grouping were repeated inside every fold and the whole pipeline was permuted, the cross-validated ability fell sharply (Table 1, Fig. 2, Fig. 3). For H. influenzae Q² fell from 0.43 to −0.14 (p = 0.15) and for S. pyogenes from 0.52 to −0.11 (p = 0.13) — neither better than the class-mean predictor and neither significant. For S. aureus and S. pneumoniae a weak but significant signal remained (nested Q² 0.16 and 0.19; p = 0.013 and 0.010). P. aeruginosa retained perfect but uninterpretable values (three actives) and is reported descriptively only."));

// Table 1: three-way comparison
push(makeTable([
 ["Strain","Active/\ninactive","Descriptors\n(A / B)","Route A apparent Q²","Route A nested Q² (p)","Route B Q² nLV=1 (p)"],
 ["H. influenzae","10 / 21","32 / 13","0.43","−0.14 (0.15) n.s.","0.29 (0.001) *"],
 ["S. aureus","5 / 26","53 / 13","0.50","0.16 (0.013) *","0.39 (0.003) *"],
 ["S. pneumoniae","6 / 25","46 / 13","0.56","0.19 (0.010) *","0.35 (0.003) *"],
 ["S. pyogenes","11 / 20","31 / 13","0.52","−0.11 (0.13) n.s.","0.06 (n.s.)"],
 ["P. aeruginosa †","3 / 28","41 / 13","0.88","0.40 (artefact)","0.82 (artefact)"],
], [1500, 1050, 1050, 1550, 1900, 1900]));
push(tblCap("Table 1|  Cross-validated predictive ability (Q²) of the three analyses and the number of descriptors entering PLS-DA. Descriptors (A / B): strain-specific representative set for Route A (correlation grouping + effect-size selection) and the fixed 13-descriptor set for Route B. Route A apparent = supervised selection before cross-validation (optimistic). Route A nested = selection repeated inside every fold with whole-pipeline permutation. Route B = literature-derived descriptors, unsupervised reduction, one latent variable. Permutation p in parentheses; * significant at p < 0.05; n.s. not significant. † P. aeruginosa has only three actives and is descriptive only. All values are from the reproducible Python pipeline (Additional files)."));

push(img("/mnt/user-data/outputs/Fig_three_way_comparison.png", 520, 436, "png"));
push(legend("2","Three-way comparison of PLS-DA validation across the five strains. Grouped bars show cross-validated Q² (top) and AUC (bottom) for Route A apparent (grey), Route A nested (orange) and Route B literature-derived, nLV = 1 (green). Asterisks mark models significant by permutation (p < 0.05); P. aeruginosa (hatched) is an artefact with only three actives. Apparent Route A performance is largely removed by nested validation, whereas the leakage-free Route B recovers a genuine signal for three strains."));

push(img("/mnt/user-data/outputs/Fig_nested_permutation_all5.png", 470, 666, "png"));
push(legend("3","Fully nested permutation test of Route A for all five strains (2,000 permutations of the entire pipeline). Histograms show the null distribution of Q² (left) and AUC (right); the observed value (solid line) is compared with the 95th percentile of the null (dashed). The observed values fall inside the null distribution for H. influenzae and S. pyogenes (not significant) and exceed it only weakly for S. aureus and S. pneumoniae."));

push(H2("Route B: a leakage-free interpretable set recovers a genuine signal"));
push(body("The 13 literature-derived descriptors, reduced only by unsupervised correlation, gave an honestly significant, moderate signal for H. influenzae, S. aureus and S. pneumoniae even with a single latent variable (Q² = 0.29, 0.39 and 0.35; AUC 0.82–0.85; p = 0.001, 0.003 and 0.003; Table 1, Fig. 2). Because the reduction uses no labels, the simple permutation test is already honest and apparent and cross-validated performance coincide. These are precisely the strains that Route A lost or weakened under nesting. S. pyogenes remained weak and non-significant (Q² = 0.06) despite having the most actives, indicating an endpoint-specific rather than a sample-size-driven effect. Under the Bonferroni threshold (α = 0.01) H. influenzae and S. pneumoniae remained significant and S. aureus was borderline (p(AUC) = 0.018)."));

push(H2("The two-stage VIP procedure reproduces the bias"));
push(body("A procedure sometimes used in the literature — fitting a first PLS-DA, keeping only high-VIP descriptors and re-fitting — was evaluated. When the VIP selection was performed on the whole dataset (naive), the subsequent Q² was consistently higher than when the VIP step was repeated inside each fold (nested); for example H. influenzae 0.29 → 0.16 and S. pneumoniae 0.53 → 0.31. The difference is the optimistic bias introduced by the label-dependent VIP selection, exactly the leakage seen for the effect-size filter. The descriptors reaching VIP > 1 for each strain are listed in the Additional file."));

// ---- top-15 subsection ----
push(H2("Does the n:p-constrained (top-15) selection rescue Route A?"));
push(body("The original design of Route A retained the 15 highest-effect-size descriptors per strain to keep the sample-to-feature ratio near 2:1. We evaluated this top-15 model with the same honest machinery (Table 1B, Fig. 2b, Fig. 3b). Constraining to 15 descriptors did not restore the apparent performance under nesting: for H. influenzae the nested Q² remained negative (−0.16, p = 0.18) and for S. aureus it fell to −0.04 (p = 0.06). More tellingly, the significance pattern shifted relative to the full representative sets — S. pyogenes now became significant (nested Q² = 0.17, p = 0.015) while S. aureus lost significance — although the underlying data were identical. This instability, in which the set of apparently significant endpoints depends on the exact size of the supervised selection, is itself a symptom of the small-n regime: keeping the n:p ratio near 2:1 is necessary but not sufficient, because the supervised selection remains label-dependent and must still be validated by nesting. S. pneumoniae remained significant under both selections, and P. aeruginosa remained an artefact."));
push(makeTable([
 ["Strain","Descriptors","Apparent Q²","Apparent AUC","Nested Q² (p)","Nested AUC (p)"],
 ["H. influenzae","15","0.49","0.93","−0.16 (0.18) n.s.","0.72 (0.055)"],
 ["S. aureus","15","0.47","0.97","−0.04 (0.061) n.s.","0.76 (0.050)"],
 ["S. pneumoniae","15","0.54","0.98","0.14 (0.012) *","0.83 (0.013) *"],
 ["S. pyogenes","15","0.50","0.95","0.17 (0.015) *","0.82 (0.007) *"],
 ["P. aeruginosa †","15","0.73","1.00","0.40 (artefact)","0.98 (artefact)"],
], [1700,1200,1350,1350,1900,1800]));
push(tblCap("Table 1B|  Route A restricted to the 15 highest-effect-size descriptors per strain (n:p ≈ 2:1), evaluated with apparent LOO-CV and fully nested validation (2,000 whole-pipeline permutations; nLV = 1). Permutation p in parentheses; * significant at p < 0.05; n.s. not significant. † P. aeruginosa (three actives) is an artefact. The significant strains differ from those obtained with the full representative sets (Table 1), illustrating the instability of supervised selection at small n."));
push(img("/mnt/user-data/outputs/Fig_three_way_comparison_top15.png", 520, 436, "png"));
push(legend("2b","Three-way comparison using the n:p-constrained top-15 descriptor set. As in Fig. 2, but Route A now uses the 15 highest-effect-size descriptors per strain (Route B unchanged). Constraining the ratio to ~2:1 does not restore Route A under nested validation and shifts which strains are significant (cf. Table 1B)."));
push(img("/mnt/user-data/outputs/Fig_nested_permutation_top15.png", 470, 666, "png"));
push(legend("3b","Fully nested permutation test of the top-15 Route A models for all five strains (2,000 permutations of the entire pipeline). Layout as in Fig. 3. Observed values are significant only for S. pneumoniae and S. pyogenes (P. aeruginosa is an artefact); H. influenzae and S. aureus remain within the null distribution."));

// ---- selection-criterion comparison (Table 1C) ----
push(H2("Effect-size versus VIP selection: the significant strains change with the criterion"));
push(body("The 15 descriptors can be chosen either by effect size or by variable importance in projection (VIP). We compared both criteria on identical data with identical apparent and fully nested validation (2,000 whole-pipeline permutations each; Table 1C, Fig. 2c). Apparent performance was comparable, but the honest (nested) verdict differed and, most importantly, the set of significant strains changed with the criterion. Under effect-size selection, S. pneumoniae and S. pyogenes were significant; under VIP selection, S. aureus and S. pyogenes were significant. S. aureus and S. pneumoniae therefore exchanged significance depending purely on the selection criterion, while only S. pyogenes remained significant under both. That the honest verdict for an endpoint depends on an essentially arbitrary methodological choice is direct evidence that, at this sample size, supervised selection is unstable and its apparent successes are not reproducible — reinforcing that only nested validation, and preferably an unsupervised or a priori descriptor choice, yields trustworthy conclusions."));
push(makeTable([
 ["Strain","Descr.","Effect-size nested Q² (p)","Effect-size nested AUC (p)","VIP nested Q² (p)","VIP nested AUC (p)"],
 ["H. influenzae","15","−0.16 (0.18) n.s.","0.72 (0.055)","−0.08 (0.12) n.s.","0.74 (0.044)"],
 ["S. aureus","15","−0.04 (0.061) n.s.","0.76 (0.050)","0.10 (0.023) *","0.82 (0.025) *"],
 ["S. pneumoniae","15","0.14 (0.012) *","0.83 (0.013) *","−0.02 (0.073) n.s.","0.79 (0.039)"],
 ["S. pyogenes","15","0.17 (0.015) *","0.82 (0.007) *","0.12 (0.029) *","0.82 (0.009) *"],
 ["P. aeruginosa †","15","0.40 (artefact)","0.98 (artefact)","0.43 (artefact)","0.99 (artefact)"],
], [1350,750,1800,1750,1550,1550]));
push(tblCap("Table 1C|  Route A top-15 selected by effect size versus by VIP, both evaluated by apparent LOO-CV and fully nested validation (2,000 whole-pipeline permutations; nLV = 1). Permutation p in parentheses; * significant at p < 0.05; n.s. not significant. † P. aeruginosa (three actives) is an artefact. The significant strains differ between the two criteria — S. aureus and S. pneumoniae exchange significance — while only S. pyogenes is significant under both."));
push(img("/mnt/user-data/outputs/Fig_selection_effsize_vs_vip.png", 500, 408, "png"));
push(legend("2c","Route A top-15 under effect-size versus VIP selection (nested validation, 2,000 permutations). Nested Q² (top) and AUC (bottom) per strain for effect-size (purple) and VIP (teal) selection; asterisks mark p < 0.05; P. aeruginosa (hatched) is an artefact. The set of significant strains depends on the selection criterion, illustrating the instability of supervised selection at small n."));

// ================= RESULTS AND DISCUSSION =================
push(H1("Results and discussion"));
push(H2("Redundancy reduction is unsupervised and comes first"));
push(body("Large descriptor pools are highly redundant: constitutional, topological and connectivity indices frequently encode the same property. Collapsing each cluster of |ρ| or |r| > 0.7 descriptors to a single representative, while keeping uncorrelated singletons, removes redundancy without discarding chemically distinct information and is fully auditable. Crucially, this step uses no activity labels, so it is leakage-free and need not be nested — an important practical point, because it means aggressive redundancy reduction on the full dataset is statistically legitimate even in the small-n regime."));
push(H2("Why both Spearman and Pearson"));
push(body("Pearson's r captures linear associations, Spearman's ρ any monotonic relationship. Using both (a pair is redundant if either exceeds 0.7) is the more conservative choice and, with count and binary descriptors at n = 31, catches monotonic-but-nonlinear redundancies that Pearson underestimates. In the interpretable set the two coefficients agreed on 25 of the redundant pairs; three were detected only by Spearman (most clearly hydrogen-bond-donor count vs. TPSA, r = 0.57 but ρ = 0.72) and two only by Pearson. The reduction differed by a single descriptor (13 vs. 14) — a representative swap within one redundant block — so the result is robust to the choice of coefficient."));
push(H2("Supervised filtering outside cross-validation invalidates apparent performance"));
push(body("The central result of this study is a cautionary one. Reducing a very large pool by correlation and then by a supervised effect-size filter, and reporting the cross-validated performance of the resulting model, appears to work — Route A gave positive apparent Q² and permutation p ≈ 0.0005 for four strains. This apparent success is, however, largely an artefact of selection bias. The effect-size filter uses the activity labels of all 31 compounds to choose descriptors; a left-out compound has therefore already influenced the selection, so the ordinary permutation test — which permutes labels only for the modelling step while holding the label-selected descriptors fixed — is circular and reports a spuriously small p. With p ≫ n some descriptors always separate a particular small dataset by chance, so this route effectively selects, and then rewards, stable noise [Ambroise & McLachlan; Varma & Simon; Rücker et al.]. When the entire selection is moved inside the cross-validation and the whole pipeline is permuted, the apparent ability disappears for H. influenzae and S. pyogenes (Q² < 0). In short: the widely used large-pool-plus-effect-size route, validated in the usual non-nested way, yields statistically invalid performance estimates. It must be checked by nested validation before any predictive claim is made."));
push(H2("The excess of univariate hits does not prove signal"));
push(body("A natural objection is that far more descriptors pass the effect-size filter than the ~110 (5 % of 2,208) expected by chance — 373 to 603 across the strains — so the surplus of several hundred descriptors ought to reflect genuine discrimination. That reasoning assumes 2,208 independent tests, which the data violate: the descriptors are strongly correlated, so the number passing by chance is not fixed near 110 but varies enormously. Permuting the class labels 1,000 times and recomputing the filter (Fig. 4) yields a null distribution with a mean of about 85–95 but a 95th percentile of ~285–300 and a maximum of 580–690, because a single fortuitous label split is echoed by whole families of correlated descriptors that pass together. The observed counts do exceed the null mean — consistent with some genuine signal, matching the strains that survive nested validation — yet they lie within the null maximum (for S. aureus the null reaches 692 against 603 observed). One therefore cannot subtract 110 and treat the remainder as real, nor identify which specific descriptors are the true positives; and because these p-values were not corrected for multiple testing, a surplus is expected even under weak signal. The honest counterpart of the excess-hits argument is the whole-pipeline permutation test, which asks whether the complete selection-and-modelling procedure predicts better than chance — and for most endpoints it does not."));
push(img("/mnt/user-data/outputs/Fig_correlation_inflation.png", 560, 137, "png"));
push(legend("4","Correlation inflates the number of descriptors passing the effect-size filter by chance. For each strain the null distribution (grey) is the count of descriptors with |r| > 0.3 and p ≤ 0.05 over 1,000 label permutations; the observed count (red) and the naïve independence expectation (5 % × 2,208 ≈ 110, dotted) are marked. Chance alone can produce up to ~580–690 hits — for S. aureus more than the 603 observed — so the surplus over 110 is not evidence that hundreds of descriptors genuinely discriminate."));
push(body("The same caution applies to visual evidence. Two-dimensional PLS-DA score plots of the selected descriptors show convincing separation of active and inactive compounds for every strain (Additional file, Figs S6–S7), including the strains that fail nested validation. Apparent separation on the training data, whether summarised as a high apparent Q², a small ordinary permutation p, or a clean score plot, is a property of fitting a flexible model to few samples in many dimensions — not evidence of predictive ability."));
push(H2("Yet nested validation can still succeed — the procedure is not worthless"));
push(body("Nesting does not simply destroy all signal. Despite only 31 compounds, several of them barely active, the fully nested analysis remained significant for S. aureus and S. pneumoniae (Q² 0.16 and 0.19; p ≤ 0.013). The supervised route can therefore be meaningful for some datasets — provided the performance is estimated by nested validation rather than by the biased non-nested procedure. The lesson is not to abandon supervised selection, but to validate it honestly: filtering is permitted, but the performance estimate must be nested."));
push(H2("A small, interpretable, unsupervised-reduced set is the statistically cleaner route"));
push(body("Route B avoids the problem at its source. Because the descriptors are fixed a priori from mechanistic knowledge and the only data-driven step (correlation grouping) is unsupervised, there is no label leakage to correct, and a simple permutation test is already honest. This route recovered a genuine, moderate and interpretable signal for three strains with a single latent variable, and its apparent and cross-validated performance agree. A pre-selected set of this kind therefore carries real, if modest, predictive value, and its descriptors can be interpreted mechanistically without the circularity that afflicts data-driven selection. The trade-off is that a priori selection is subjective; but subjectivity that is transparent and label-independent is preferable, in the small-n regime, to an objective-looking but leaky data-driven filter."));
push(H2("Disadvantages of two-stage VIP-based selection"));
push(body("Selecting descriptors by VIP in a first model and re-using only the high-VIP ones in a second is attractive but has two drawbacks. First, VIP is a model-internal quantity: the mean squared VIP is 1 by construction, so some descriptors exceed 1 in every model, including one fitted to noise; VIP > 1 is a ranking heuristic within an already-validated model, not independent evidence of predictive value. Second, and more seriously, VIP is computed from the labels, so selecting on it outside cross-validation is the same leakage as any supervised filter — our naive-versus-nested comparison shows the resulting Q² is inflated (e.g. 0.29 vs. 0.16). We therefore recommend using VIP only for interpretation within a validated model; if it is used for selection, that selection must be nested. With a well-chosen a priori set the second VIP stage is usually unnecessary, because the reduced set already models honestly."));
push(H2("Why the n:p ratio governs the whole design"));
push(body("All of the above is a consequence of the n:p ratio. At n = 31 the data support only a few effective dimensions; feeding a large pool into PLS-DA guarantees apparent separation, and even a modest supervised filter can manufacture it. Reducing p — unsupervised where possible — and reporting one- or two-component models keeps the ratio in the range where the cross-validated estimate is meaningful. The rule p ≤ n/2 is a useful ceiling, but it is not sufficient on its own: a 15-descriptor model with a supervised, non-nested selection is still biased. The n:p constraint and honest (nested) validation are complementary, not interchangeable. The exchange of significant strains between the two selection criteria (Table 1C, Fig. 2c) is a further symptom of this instability: when the honest verdict for an endpoint flips with an arbitrary methodological choice, the apparent signal is not reproducible."));
push(H2("Mechanistic interpretability of the retained descriptors"));
push(body("The descriptors retained by Route B are consistent with the known determinants of monoterpenoid antibacterial activity — hydrogen-bonding capacity, molecular size/surface and lipophilicity, together with functional-group indicators (phenol, carbonyl, alcohol) — in line with the reported membrane-directed mode of action [Griffin et al.; refs]. That a leakage-free, label-independent reduction retains mechanistically plausible descriptors supports the interpretation that the Route-B models reflect a real, if moderate, structure–activity relationship rather than a numerical artefact."));
push(H2("Effect of class balance"));
push(body("Because activity was defined by MIC, the active/non-active split is not balanced (from 3/28 to 11/20). At this scale, moderate imbalance affects power only marginally; the dominant constraint is n:p. A more subtle point is that the supervised effect-size filter is unstable under strong imbalance: with very few actives, more descriptors pass the filter by chance (P. aeruginosa retained more features than the better-balanced strains), which is a symptom of instability rather than of stronger discrimination and reinforces the need for nested validation."));

// ================= CONCLUSIONS =================
push(H1("Conclusions"));
push(body("Using 31 monoterpenoids against five bacterial strains, we compared the two descriptor-selection routes that dominate small-sample QSAR and examined how they should be validated. Our central finding is methodological: the popular route of computing a very large descriptor pool, reducing it by correlation and a supervised effect-size (or VIP) filter, and reporting the cross-validated performance of the resulting model, produces optimistically biased and effectively invalid performance estimates, because the label-based selection is performed outside cross-validation and the usual permutation test is then circular. Only fully nested validation, with the selection repeated inside every fold and the whole pipeline permuted, gives an honest estimate — under which the apparent ability collapsed for two of the four ostensibly significant strains. Nevertheless, and despite very few and weakly active compounds, a genuine signal survived nesting for two strains, so the supervised route can be worthwhile for some datasets when validated honestly. The complementary route — a small, mechanistically chosen, interpretable descriptor set reduced only by unsupervised correlation — is leakage-free by construction, recovered a genuine moderate signal for three strains, and is our recommended default for the small-n regime."));
push(new Paragraph({ spacing:{before:60,after:60}, children:[new TextRun({text:"Recommendations for descriptor selection under an unfavourable n:p ratio.", bold:true, font:FONT, size:22})]}));
push(body("Synthesising these results, we suggest the following for datasets where p approaches or exceeds n: (1) Prefer a small, mechanistically motivated, interpretable descriptor set over an exhaustive data-driven pool; theory-based pre-selection is subjective but label-independent and therefore leakage-free. (2) Reduce residual redundancy by unsupervised correlation grouping (Spearman or Pearson > 0.7); this may be done on the full dataset without bias. (3) Keep any supervised selection (effect-size, VIP, wrappers) strictly inside the cross-validation; never select on labels using all data and then report the cross-validated score of the reduced model. (4) Report the nested cross-validated Q²/AUC as the performance estimate and the apparent values only as goodness-of-fit; validate significance by permuting the entire pipeline, not just the final model. (5) Respect the n:p ceiling (p ≤ n/2 as a guide) and prefer one- to two-component models. (6) Correct for multiplicity across endpoints, and treat all results as hypothesis-generating until confirmed on an external test set. Descriptors selected in this way should be described as associated with activity in the dataset, not as validated predictors of new compounds. Following these steps, honest and interpretable structure–activity signals can be extracted even from small, imperfect datasets, while the spurious models that an unfavourable n:p ratio would otherwise produce are avoided."));

// ================= DECLARATIONS =================
push(H1("Declarations"));
push(H3("Ethics approval and consent to participate"));
push(body("Not applicable. Only ATCC bacterial reference strains were used; the study involved no human participants, human data or animals."));
push(H3("Consent for publication")); push(body("Not applicable."));
push(H3("Availability of data and materials"));
push(body("All descriptor tables, correlation matrices, per-strain PLS-DA and nested-validation results, VIP tables and the complete analysis scripts (Python/RDKit) are provided as Additional files, so that every result is reproducible by third parties. The underlying biological activity data were reported previously [Werle et al. 2026]."));
push(H3("Competing interests")); push(body("The authors declare that they have no competing interests."));
push(H3("Funding")); push(body("No funding was received for this work."));
push(H3("Authors' contributions"));
push(body("JW generated the experimental data of the case study, conceived the case study, performed statistical calculations, and contributed to methodology and the writing of the original manuscript. EW performed the statistical validation and contributed to the discussion, the writing of the original manuscript, visualization, validation, conceptualization and methodology. JR contributed to writing (review and editing), project administration and supervision. All authors read and approved the final manuscript."));
push(H3("Acknowledgements"));
push(body("The authors thank Anna Mascellani (Czech University of Life Sciences Prague) for helpful statistical advice."));

// ================= FIGURE LEGENDS (list) =================
push(H1("Figure legends"));
push(P([T("Fig. 1 ",{bold:true}), T("Overview of the two descriptor-selection routes and the validation strategy (main text).")]));
push(P([T("Fig. 2 ",{bold:true}), T("Three-way comparison of PLS-DA validation across the five strains (main text).")]));
push(P([T("Fig. 2b ",{bold:true}), T("Three-way comparison using the n:p-constrained top-15 descriptor set (main text).")]));
push(P([T("Fig. 2c ",{bold:true}), T("Route A top-15 under effect-size versus VIP selection, nested validation (main text).")]));
push(P([T("Fig. 3 ",{bold:true}), T("Fully nested permutation test of Route A (full representative sets) for all five strains (main text).")]));
push(P([T("Fig. 3b ",{bold:true}), T("Fully nested permutation test of the top-15 Route A models for all five strains (main text).")]));
push(P([T("Fig. 4 ",{bold:true}), T("Correlation inflates the number of descriptors passing the effect-size filter by chance (main text).")]));

// ================= SUPPLEMENTARY =================
push(H1("Supplementary Information"));
push(P([T("Additional file 1 (spreadsheet). ",{bold:true}), T("Route B descriptor definitions and exact SMARTS, descriptor values for all 31 compounds, Pearson and Spearman correlation matrices, correlation-based reduction, per-strain PLS-DA results (nLV = 1 and Q²-optimal), VIP scores and VIP > 1 lists, and the two-stage VIP (naive vs. nested) comparison.")]));
push(P([T("Additional file 2 (spreadsheet). ",{bold:true}), T("Route A cleaned descriptor matrix (2,208 descriptors), per-strain effect-size reduction sheets and apparent PLS-DA results.")]));
push(P([T("Additional file 3 (spreadsheet). ",{bold:true}), T("Per-strain VIP and effect-size tables, separated by descriptor world (ChemDes / Route A top-15 and the literature set), with apparent VIP, mean nested VIP across folds, selection frequency and effect size.")]));
push(P([T("Additional file 4 (spreadsheet). ",{bold:true}), T("Effect-size versus VIP selection comparison for the Route A top-15 models (apparent and nested Q²/AUC with permutation p; underlying values of Table 1C).")]));
push(P([T("Additional file 5 (archive). ",{bold:true}), T("Python/RDKit analysis scripts and permutation outputs reproducing all descriptor calculations, correlation reductions, nested cross-validation and permutation tests.")]));
push(P([T("Fig. S1. ",{bold:true}), T("Detailed nested permutation test for H. influenzae (Q² and AUC null distributions; single-strain example of Fig. 3).")]));
push(P([T("Fig. S2. ",{bold:true}), T("Representative correlation structure and feature-group assignment (Route A, Stage 2).")]));
push(P([T("Fig. S3. ",{bold:true}), T("VIP scores per descriptor for the Route A top-15, Route B and two-stage-VIP models across the five strains (apparent vs. mean nested VIP).")]));
push(P([T("Fig. S4. ",{bold:true}), T("VIP curves (VIP versus descriptor) for the Route B and two-stage-VIP descriptor sets, all strains overlaid, and per-strain curves for the Route A top-15.")]));
push(P([T("Fig. S5. ",{bold:true}), T("One-component (LV1) apparent class separation for the Route A top-15 models: comparison of strip, box-and-jitter and violin displays, and box-and-jitter for all five strains.")]));
push(P([T("Fig. S6. ",{bold:true}), T("Two-dimensional MetaboAnalyst-style PLS-DA score plots (samples; active red, non-active green; 95 % confidence ellipses) for all five strains, Route A top-15.")]));
push(authorNote("Verbleibend: Software-/Domänenreferenzen als nummerierte Zitate ergänzen (siehe Referenzliste)."));

// ================= REFERENCES =================
push(H1("References"));
const refs = [
 "Ambroise C, McLachlan GJ (2002) Selection bias in gene extraction on the basis of microarray gene-expression data. Proc Natl Acad Sci USA 99:6562–6566.",
 "Varma S, Simon R (2006) Bias in error estimation when using cross-validation for model selection. BMC Bioinformatics 7:91.",
 "Krstajic D, Buturovic LJ, Leahy DE, Thomas S (2014) Cross-validation pitfalls when selecting and assessing regression and classification models. J Cheminform 6:10.",
 "Cawley GC, Talbot NLC (2010) On over-fitting in model selection and subsequent selection bias in performance evaluation. J Mach Learn Res 11:2079–2107.",
 "Golbraikh A, Tropsha A (2002) Beware of q2! J Mol Graph Model 20:269–276.",
 "Rücker C, Rücker G, Meringer M (2007) y-Randomization and its variants in QSPR/QSAR. J Chem Inf Model 47:2345–2357.",
 "Tropsha A (2010) Best practices for QSAR model development, validation, and exploitation. Mol Inform 29:476–488.",
 "Gramatica P (2007) Principles of QSAR models validation: internal and external. QSAR Comb Sci 26:694–701.",
 "Hawkins DM (2004) The problem of overfitting. J Chem Inf Comput Sci 44:1–12.",
 "Wold S, Sjöström M, Eriksson L (2001) PLS-regression: a basic tool of chemometrics. Chemometr Intell Lab Syst 58:109–130.",
 "Chong I-G, Jun C-H (2005) Performance of some variable selection methods when multicollinearity is present. Chemometr Intell Lab Syst 78:103–112.",
 "Wildman SA, Crippen GM (1999) Prediction of physicochemical parameters by atomic contributions. J Chem Inf Comput Sci 39:868–873.",
 "Ertl P, Rohde B, Selzer P (2000) Fast calculation of molecular polar surface area as a sum of fragment-based contributions and its application to the prediction of drug transport properties. J Med Chem 43:3714–3717.",
 "Landrum G (2024) RDKit: open-source cheminformatics. https://www.rdkit.org. Accessed 2026.",
 "Pedregosa F, Varoquaux G, Gramfort A et al (2011) Scikit-learn: machine learning in Python. J Mach Learn Res 12:2825–2830.",
 "[AUTHORS → add: Werle et al. 2026 (biological SAR companion study); Ruiz-Pérez et al. (PLS-DA n:p simulation); Yap 2011 (PaDEL); Cao et al. (Chemopy); Dong et al. (ChemDes); Kim et al. (PubChem); OECD QSAR Toolbox; Pang/Xia et al. (MetaboAnalyst); Comesaña et al.; Griffin et al.; Cohen 1988; Benjamini & Hochberg 1995; Westerhuis et al. 2008].",
];
refs.forEach((r,i)=> push(new Paragraph({ spacing:{after:60,line:252}, children:[
  new TextRun({text:(i+1)+". ", bold:true, font:FONT, size:20}), new TextRun({text:r, font:FONT, size:20})]})));
push(authorNote("Referenzen: Nr. 1–15 sind gegen Primärquellen verifiziert (J-Cheminform-Stil, Autor-Jahr, nummeriert). Die domänenspezifischen/Software-Referenzen aus eurem Entwurf (Nr. 16) bitte ergänzen und in Auftrittsreihenfolge final durchnummerieren. Im Text die [Name]-Platzhalter durch die entsprechenden Nummern ersetzen."));

// ---------- document ----------
const doc = new Document({
  creator:"Werle et al.",
  styles:{ default:{ document:{ run:{ font:FONT, size:22 } } } },
  sections:[{ properties:{ page:{ margin:{ top:1440,bottom:1440,left:1440,right:1440 } } }, children }]
});
Packer.toBuffer(doc).then(b=>{ fs.writeFileSync("/mnt/user-data/outputs/Werle_JCheminform_revised_Claude_2026-07-10.docx", b);
  console.log("written"); });
